### ISSUE TITLE
Atualização de dependências

### ISSUE THREAD

**Issue by vgeorge** [mapascoletivos/api#46]
O objetivo desta issue é discutir mudanças necessárias para atualizar as dependências do Mapas Coletivos, no backend e frontend. O trabalho está sendo feito nos branches `develop` do api-service e webapp:

https://github.com/mapascoletivos/api-service/tree/develop
https://github.com/mapascoletivos/webapp/tree/develop

**Comment by thiagopaixao** [comment]
As configurações que estou usando:

## docker-composer.yml
version: '2'
services:
  api:
    build: api-service/.
    command: npm run start
    links:
      - mongo
    ports:
    - 3100:3000
    volumes:
    - /src/node_modules
    - ./api-service/:/src
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo/mapascoletivos

  app:
    build: webapp/.
    command: nodemon server.js
    ports:
    - 8000:8000
    volumes:
    - /src/node_modules
    - ./webapp/:/src
    environment:
      NODE_ENV: development
      SITE_URL: http://173.212.229.224:8000
      SERVER_URL: http://173.212.229.224:3100
      API_PREFIX: /api/v1

  mongo:
    image: mongo:3.2
    #ports:
    #- 27018:27017

##webapp/app/config.js
'use strict';

var env = process.env;

module.exports = {
	siteUrl: env.SITE_URL || 'http://173.212.229.224:8000', // Client URL. Eg: http://my-yby-service.com
	server: env.SERVER_URL || 'http://173.212.229.224:3100', // Server URL. Eg: http://server.my-yby-service.com
	apiPrefix: env.API_PREFIX || '/api/v1' // You probably won't change this
};

**Comment by vgeorge** [comment]
Subi uma alteração que resolve este erro do Mongoose. O parâmetro `limit` precisava ser transformado em inteiro.

**Comment by thiagopaixao** [comment]
Olá

Fiz a atualização, consegui subrir a aplicação, mas alguns erros persistem.
Segue uma descrição dos problemas relatados pelo Stefano:

- Em todo o site o seguinte erro aparece no console: Missing appId setting
- Em páginas de mapas como esta o seguinte erro aparece no console: ReferenceError: angular is not defined.
- No painel de controle do usuário logado vários erros CORS aparecem no console. Exemplo: Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://173.212.229.224:3000/api/v1/user/maps?page=1&perPage=10.
- No painel de controle do usuário logado nenhum conteúdo – como mapas e camadas criadas e biografia – aparece
- As camadas desta página não estão rodando. Isto pode ser o motivo pelo qual a página "Explorar" mostre, no topo, várias vezes um banner vermelho com o erro Camada não está definida.

**Comment by thiagopaixao** [comment]
Para rodar o Mapas Coletivos no estágio atual, foi feito o seguinte procedimento:

**API-Service**

- Foi realizado o clone da última versão do repositório e usado o branch enhance/node-8-upgrade-origin;
- Na primeira execução, acessei http://host/admin para criar um primeiro usuário administrador.
- Acessei o painel com o usuário criado e configurei conforme o README
- Em seguida importei o dump do banco de dados do servidor antigo


**Webapp**

- Foi realizado o clone da última versão do repositório
- Instalei o tema no Mapas Coletivos
- Editei o arquivo app/config.js para aplicar o tema e direcionar para o ip do API-Service

**Comment by vgeorge** [comment]
@bwstefano uma dúvida, os erros relatados pelo @thiagopaixao ocorrem no ambiente de produção? Não consegui replicá-los localmente. 

@thiagopaixao Renomeei o branch de trabalho para `develop`, tanto aqui como no webapp.

**Comment by thiagopaixao** [comment]
Olá Vitor

Os erros ocorrem na tentativa de implementação e migração para o novo
servidor.
Estou fazendo usando containers Docker.

Se pudesse disponiblizar uma imagem docker pronta, e um docker-composer com
os parametros corretos (com as variaveis de parametros de prodrução),
acredito que nos ajudaria muito.

Obrigado

Em qua, 24 de abr de 2019 às 07:48, Vitor George <notifications@github.com>
escreveu:

**Comment by vgeorge** [comment]
@thiagopaixao agora é possível iniciar o Mapas Coletivos como instância Docker:

https://hub.docker.com/r/mapascoletivos/api

Por favor, confirme se consegue fazer rodar.

**Comment by thiagopaixao** [comment]
Consegui rodar pela imagem do Docker, e parece que funcionou redondo.
Muito obrigado!

Em dom, 26 de mai de 2019 às 09:17, Vitor George <notifications@github.com>
escreveu:

**Comment by vgeorge** [comment]
Que ótimo!
