### ISSUE TITLE
Missing links in "reset password" and "activate account" e-mails

### ISSUE THREAD

**Issue by vgeorge** [mapascoletivos/api#56]

**Comment by vgeorge** [comment]
@bwstefano this was a issue at the e-mail templates. Could you please review at the staging enviroment?

**Comment by bwstefano** [comment]
Didn't receive any email to activate my account. The link in the email to reset password worked fine, though. URL started with http://mc1-dev.herokuapp.com/new_password/

**Comment by vgeorge** [comment]
Activation was disabled, could you please check again?

**Comment by vgeorge** [comment]
Status update: the link is included in the e-mail, but an error at the activation route is returned.

**Comment by vgeorge** [comment]
Found the error and pushed a fix in https://github.com/mapascoletivos/api/pull/59. I was able to create a user and recieved e-mail confirmation at the staging enviroment.
